<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LeadStatusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        \DB::table('lead_status_level')->delete();
        \DB::table('lead_status_level')->insert([
            [
                'level' => '0',
                'comments' => 'Lead assigned by system',
            ],
            [
                'level' => '1',
                'comments' => 'Lead transfer from admin to BDE Team Lead',
            ],
            [
                'level' => '2',
                'comments' => 'Lead transfer from BDE Team Lead to BDE Intern',
            ],
            [
                'level' => '3',
                'comments' => 'Lead transfer from BDE Intern Lead to Demo Manager',
            ],
            [
                'level' => '4',
                'comments' => 'Lead transfer from Demo Manager to Demo Trainer',
            ],
            [
                'level' => '5',
                'comments' => 'Lead transfer from Demo Trainer to BDM Team Lead',
            ],
            [
                'level' => '6',
                'comments' => 'Lead transfer from BDM Team Lead to BDE Junior',
            ],
            [
                'level' => '7',
                'comments' => 'Lead transfer from BDE Junior to QA',
            ],
            [
                'level' => '8',
                'comments' => 'Lead transfer from Demo Trainer to Class Trainer',
            ],
            
            [
                'level' => '9',
                'comments' => 'Lead generated by own(Team Lead / Trainer)',
            ],
            
        ]);
    }
}
